exp_dir: null
exp_name: null
gpus: null
slurm_job_id: null
file_path: null
ckpt_path: null
pretrained_model_path: /work/lixiaolou/program/auto_avsr/pretrained_model/vsr_trlrwlrs2lrs3vox2avsp_base.pth
transfer_frontend: null
transfer_encoder: null
data:
  modality: video
  use_audio_normalise: false
  max_frames: 1800
  max_frames_val: 500
  dataset:
    root_dir: /ssd1/data/processed/LRS3
    label_dir: labels
    train_file: lrs3_train_transcript_lengths_seg24s.csv
    val_file: lrs3_test_transcript_lengths_seg24s.csv
    test_file: lrs3_test_transcript_lengths_seg24s.csv
model:
  visual_backbone:
    adim: 768
    aheads: 12
    eunits: 3072
    elayers: 12
    transformer_input_layer: conv3d
    dropout_rate: 0.1
    transformer_attn_dropout_rate: 0.1
    transformer_encoder_attn_layer_type: rel_mha
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 31
    zero_triu: false
    a_upsample_ratio: 1
    relu_type: swish
    ddim: 768
    dheads: 12
    dunits: 3072
    dlayers: 6
    lsm_weight: 0.1
    transformer_length_normalized_loss: false
    mtlalpha: 0.1
    ctc_type: builtin
    rel_pos_type: latest
  audio_backbone:
    adim: 768
    aheads: 12
    eunits: 3072
    elayers: 12
    transformer_input_layer: conv1d
    dropout_rate: 0.1
    transformer_attn_dropout_rate: 0.1
    transformer_encoder_attn_layer_type: rel_mha
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 31
    zero_triu: false
    a_upsample_ratio: 1
    relu_type: swish
    ddim: 768
    dheads: 12
    dunits: 3072
    dlayers: 6
    lsm_weight: 0.1
    transformer_length_normalized_loss: false
    mtlalpha: 0.1
    ctc_type: builtin
    rel_pos_type: latest
  audiovisual_backbone:
    adim: 768
    aheads: 12
    eunits: 3072
    elayers: 12
    transformer_input_layer: conv3d
    dropout_rate: 0.1
    transformer_attn_dropout_rate: 0.1
    transformer_encoder_attn_layer_type: rel_mha
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 31
    zero_triu: false
    a_upsample_ratio: 1
    relu_type: swish
    ddim: 768
    dheads: 12
    dunits: 3072
    dlayers: 6
    lsm_weight: 0.1
    transformer_length_normalized_loss: false
    mtlalpha: 0.1
    ctc_type: builtin
    rel_pos_type: latest
    aux_adim: 768
    aux_aheads: 12
    aux_eunits: 3072
    aux_elayers: 12
    aux_transformer_input_layer: conv1d
    aux_dropout_rate: 0.1
    aux_transformer_attn_dropout_rate: 0.1
    aux_transformer_encoder_attn_layer_type: rel_mha
    aux_macaron_style: true
    aux_use_cnn_module: true
    aux_cnn_module_kernel: 31
    aux_zero_triu: false
    aux_a_upsample_ratio: 1
    aux_relu_type: swish
    aux_dunits: 3072
    aux_dlayers: 6
    aux_lsm_weight: 0.1
    aux_transformer_length_normalized_loss: false
    aux_mtlalpha: 0.1
    aux_ctc_type: builtin
    aux_rel_pos_type: latest
    fusion_hdim: 8192
    fusion_norm: batchnorm
optimizer:
  name: adamw
  lr: 0.001
  warmup_epochs: 5
  weight_decay: 0.03
trainer:
  precision: 32
  max_epochs: 75
  num_nodes: 1
  gpus: -1
  sync_batchnorm: true
  default_root_dir: null
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  gradient_clip_val: 5.0
  replace_sampler_ddp: false
  resume_from_checkpoint: null
decode:
  name: default
  snr_target: 999999
