defaults:
  - _self_
  - data: default
  - model: default
  - optimizer: adamw
  - trainer: train
  - decode: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:  
  output_subdir: null  
  run:  
    dir: .
exp_dir:
exp_name:
gpus: 
slurm_job_id:
file_path: /work/lixiaolou/program/auto_avsr/data/FakeAVCeleb/label_test_updated.csv
ckpt_path: /work/lixiaolou/program/auto_avsr/pretrained_model/avsr_trlrwlrs2lrs3vox2avsp_base.pth
audio_ckpt_path: /work/lixiaolou/program/auto_avsr/pretrained_model/asr_trlrwlrs2lrs3vox2avsp_base.pth
video_ckpt_path: /work/lixiaolou/program/auto_avsr/pretrained_model/vsr_trlrwlrs2lrs3vox2avsp_base.pth
pretrained_model_path:
transfer_frontend:
transfer_encoder:
device: 'cuda'
infer_path: /work/lixiaolou/program/auto_avsr/infer/fakeavceleb_ctc.json
asr_infer_path:

